### ISSUE TITLE
Geolocation does not work anymore

### ISSUE THREAD

**Issue by siamkreative** [SiamKreative/Contract-Killer-Generator#13]
From [telize.com](http://www.telize.com/)

> The public API will permanently shut down on November 15th, 2015. More information can be found here.
> To continue using Telize after this date, please spin up your own instance or subscribe to a paid plan.

Need a replacement for this...

**Comment by OmgImAlexis** [comment]
@SiamKreative https://siamkreative-ckg.surge.sh/ doesn't seem to be updated with this fix.
